name: Update database hourly

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  get-request:
    runs-on: ubuntu-latest
    steps:
      - name: Make GET request
        run: |
          curl -X GET https://spot-hinta.vercel.app/api/updatedb \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET_GITHUB }}" \
          -H "Content-Type: application/json"
